language: bash
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gawk
script:
  # ファイル構成が等しいことを確認
  - en="$(ls original-en | tr -d [:cntrl:][:space:])"
  - ja="$(ls translation-ja | tr -d [:cntrl:][:space:])"
  - if test "${en}" != "${ja}"; then echo ディレクトリ中のMarkdownファイルの構成が一致しません。; exit 1; fi
  # 各ファイルの構成が一致することを確認
  - for i in $(ls translation-ja); do if test $(awk -f scripts/structure-to-string.awk "original-en/${i}") != $(awk -f scripts/structure-to-string.awk "translation-ja/${i}"); then echo 日英ファイルの構造が一致しません "${i}"; echo $(awk -f scripts/structure-to-string.awk "original-en/${i}"); echo $(awk -f scripts/structure-to-string.awk "translation-ja/${i}"); exit 1; fi; done
  # 用語の不統一がないことを確認
  - bash scripts/check-synonyms.sh

